import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createStore,validateScene} from '../project-store.mjs';
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jwm-project-test-'));fs.mkdirSync(path.join(dir,'public/project'),{recursive:true});for(const file of['scene.json','shots.json'])fs.copyFileSync(new URL('../public/project/'+file,import.meta.url),path.join(dir,'public/project',file));return{dir,store:createStore(dir),clean:()=>fs.rmSync(dir,{recursive:true,force:true})};}
test('scene approval is blocked until camera measurements pass',()=>{const f=fixture();try{const p=f.store.read();assert.throws(()=>f.store.approve(p.revision),e=>e.status===422);assert.equal(f.store.read().approval.status,'ready_for_review');}finally{f.clean();}});
test('successful formal approval creates a new revision and preserves previous evidence',()=>{const f=fixture();try{const p=f.store.read();p.quality.cameraMeasurement='passed';fs.writeFileSync(path.join(f.dir,'data/project.json'),JSON.stringify(p,null,2));fs.writeFileSync(path.join(f.dir,'data/revisions',p.revision+'.json'),JSON.stringify(p,null,2));const oldBytes=fs.readFileSync(path.join(f.dir,'data/revisions',p.revision+'.json'),'utf8');const approved=f.store.approve(p.revision);assert.notEqual(approved.revision,p.revision);assert.equal(approved.approval.status,'approved');assert.equal(approved.approval.sceneRevision,p.scene.revision);assert.ok(Number.isFinite(Date.parse(approved.approval.time)));assert.equal(approved.history.length,p.history.length+1);assert.equal(approved.history.at(-1).revision,approved.revision);assert.equal(approved.history.at(-1).sceneRevision,p.scene.revision);assert.equal(approved.quality.cameraMeasurement,'passed');assert.equal(fs.readFileSync(path.join(f.dir,'data/revisions',p.revision+'.json'),'utf8'),oldBytes);assert.deepEqual(createStore(f.dir).read(),approved);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(f.dir,'data/revisions',approved.revision+'.json'),'utf8')),approved);assert.throws(()=>f.store.approve(p.revision),e=>e.status===409);}finally{f.clean();}});
test('saving scene creates a revision, preserves original and survives reopen',()=>{const f=fixture();try{const p=f.store.read();const original=structuredClone(p);p.scene.nodes[1].position[0]+=1;const next=f.store.update(p.revision,p.scene,'墓墙位置调整');assert.notEqual(next.revision,p.revision);assert.equal(next.quality.cameraMeasurement,'pending');const reopened=createStore(f.dir).read();assert.equal(reopened.feedback,'墓墙位置调整');assert.deepEqual(reopened.scene,next.scene);const previous=JSON.parse(fs.readFileSync(path.join(f.dir,'data/revisions',p.revision+'.json'),'utf8'));assert.deepEqual(previous.scene,original.scene);}finally{f.clean();}});
test('stale writes and stale approvals cannot overwrite the current scene',()=>{const f=fixture();try{const p=f.store.read();const next=f.store.update(p.revision,p.scene,'first');assert.throws(()=>f.store.update(p.revision,p.scene,'stale'),e=>e.status===409);assert.throws(()=>f.store.approve(p.revision),e=>e.status===409);assert.equal(f.store.read().revision,next.revision);}finally{f.clean();}});
test('invalid transforms are rejected before saving',()=>{const f=fixture();try{const p=f.store.read();p.scene.nodes[1].position[0]=Infinity;assert.throws(()=>validateScene(p.scene));assert.equal(f.store.read().revision,'project-r1');}finally{f.clean();}});
test('source cuts cover every source frame exactly and S08 starts at frame98',()=>{const shots=JSON.parse(fs.readFileSync(new URL('../public/project/shots.json',import.meta.url),'utf8'));assert.equal(shots.length,47);let end=0;for(const s of shots){assert.equal(s.startFrame,end);assert.ok(s.endFrameExclusive>s.startFrame);end=s.endFrameExclusive;}assert.equal(end,1203);assert.equal(shots[7].startFrame,98);});
