import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SceneViewport} from './SceneViewport';
import type {Project,SceneAsset} from './types';
import './style.css';

const stages=['场景还原','角色确认','关键姿态','完整镜头','导出交付'];
const time=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toFixed(2).padStart(5,'0')}`;
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await r.json();if(!r.ok)throw new Error(result.error||'读取失败');return result;}
function App(){
  const[project,setProject]=useState<Project|null>(null),[draft,setDraft]=useState<SceneAsset|null>(null),[shotId,setShotId]=useState('S15'),[mode,setMode]=useState<'shot'|'free'|'top'>('free'),[grid,setGrid]=useState(false),[selected,setSelected]=useState(''),[feedback,setFeedback]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[at,setAt]=useState<'start'|'middle'|'end'>('middle'),[showVideo,setShowVideo]=useState(false);
  const video=useRef<HTMLVideoElement>(null);
  const feedbackInput=useRef<HTMLTextAreaElement>(null);
  const showComparison=()=>document.getElementById('scene-comparison')?.scrollIntoView({behavior:'smooth',block:'center'});
  const inspectShot=(id:string)=>{setShotId(id);setMode('shot');setAt('middle');setShowVideo(false);showComparison();};
  const noteCurrentShot=()=>{const label=at==='start'?'开始帧':at==='end'?'结束帧':'中间帧';const prefix=`[${shotId} · ${label}] `;setFeedback(value=>`${value.trimEnd()}${value.trim()?'\n':''}${prefix}`);setDirty(true);requestAnimationFrame(()=>{feedbackInput.current?.focus({preventScroll:true});feedbackInput.current?.scrollIntoView({behavior:'smooth',block:'center'});});};
  const load=()=>request('/api/project').then(p=>{setProject(p);setDraft(p.scene);setFeedback(p.feedback);setSelected(p.scene.nodes.find((n:any)=>n.type==='tomb')?.id||p.scene.nodes[0]?.id||'');setDirty(false);}).catch(e=>setMessage(e.message));
  useEffect(()=>{load();},[]);
  const shot=project?.shots.find(s=>s.id===shotId)||project?.shots[0];
  const referenceFrame=shot?(at==='start'?shot.startFrame:at==='end'?shot.endFrameExclusive-1:Math.floor((shot.startFrame+shot.endFrameExclusive-1)/2)):0;
  useEffect(()=>{if(video.current){video.current.pause();video.current.currentTime=referenceFrame/24;}},[referenceFrame,showVideo]);
  const seekReference=()=>{if(video.current)video.current.currentTime=referenceFrame/24;};
  const selectedNode=draft?.nodes.find(n=>n.id===selected);
  const changeNode=(axis:number,value:number)=>{if(!Number.isFinite(value))return;setDraft(prev=>prev?{...prev,nodes:prev.nodes.map(n=>n.id===selected?{...n,position:n.position.map((v,i)=>i===axis?value:v) as [number,number,number]}:n)}:prev);setDirty(true);};
  const save=async()=>{if(!project||!draft)return;setBusy(true);try{const p=await request('/api/scene',{baseRevision:project.revision,scene:draft,feedback});setProject(p);setDraft(p.scene);setDirty(false);setMessage('已保存场景修改和意见。前一版本保留。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const confirmScene=async()=>{if(!project||dirty)return;setBusy(true);try{const p=await request('/api/approve-scene',{baseRevision:project.revision});setProject(p);setDraft(p.scene);setMessage('场景已正式确认；角色资产制作待开始。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const rehearseNext=async()=>{if(!project||dirty)return;setBusy(true);try{let run=await request('/api/rehearsal/start',{baseRevision:project.revision});if(run.currentStage===1&&run.status==='active')run=await request('/api/rehearsal/advance',{baseRevision:run.revision,stage:1});window.location.assign('/?mode=rehearsal');}catch(e){setMessage((e as Error).message);setBusy(false);}};
  if(!project||!draft)return <div className="loading"><span className="brand-mark">M</span><h1>正在打开场景工作台</h1><p>{message||'载入原片镜头与固定场景…'}</p><button onClick={load}>重新载入</button></div>;
  const camera=draft.cameras.find(c=>c.shotId===shot?.id);
  return <><header className="topbar"><div className="identity"><span className="brand-mark">M</span><div><strong>MotionStage <i>/</i> 三维复现</strong><small>从原片到可交付的三维预演</small></div></div><div className="top-meta"><span className="status-dot"/>固定场景初稿<span className="version">M0 → M1</span></div><a className="quiet-link" href="/">混剪项目 ↗</a><a className="quiet-link" href="/?mode=rehearsal">流程演练 ↗</a><a className="quiet-link" href="/?lab=rig">角色结构试验 ↗</a></header>
  <nav className="stagebar">{stages.map((s,i)=><div className={`stage ${i===0?'active':'locked'}`} key={s}><span>{i+1}</span><b>{s}</b><small>{i===0?'制作中':'待前一步确认'}</small>{i<4&&<em>›</em>}</div>)}</nav>
  <div className="workspace"><aside className="shots-panel"><div className="panel-title"><h2>原片镜头</h2><span>47 镜</span></div><p className="muted intro">所有镜头共用同一个场景</p><div className="shot-list">{project.shots.map(s=><button key={s.id} className={`shot-card ${s.id===shotId?'selected':''}`} onClick={()=>{setShotId(s.id);setMode('shot');setAt('middle');setShowVideo(false);}}><div><b>{s.id}</b><span>{s.seconds.toFixed(2)}s</span></div><p>{s.frame}</p><small>{time(s.start)} — {time(s.end)}</small></button>)}</div></aside>
  <main><div className="main-heading"><div><span className="eyebrow">01 / ENVIRONMENT</span><h1>先检查这片场地</h1><p>检查布局、地形和主要地物。此阶段的三维场景中没有角色。</p></div><a className="outline-pill" href="#review-guide">如何核对与反馈 ↓</a></div>
    <div className="viewer-toolbar"><div className="segmented">{([['shot','镜头视角'],['free','自由观察'],['top','俯视场地']] as const).map(([k,label])=><button key={k} className={mode===k?'chosen':''} onClick={()=>setMode(k)}>{label}</button>)}</div><label className="toggle"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>场地网格</label><span className="toolbar-hint">{mode==='shot'?`${shot?.id} · 初步机位`:'拖动旋转 · 滚轮拉近 · 右键平移'}</span></div>
    <section className="comparison" id="scene-comparison"><div className="view-pane"><div className="view-title"><b>三维空场景</b><span>固定布局</span></div><SceneViewport asset={draft} shotId={shotId} mode={mode} grid={grid} onSelect={setSelected}/></div><div className="view-pane"><div className="view-title"><b>原片参考 · {shot?.id}</b><span>{showVideo?"原片播放":`${time(referenceFrame/24)} · 第 ${referenceFrame+1} 帧`}</span><button className="reference-mode" onClick={()=>setShowVideo(v=>!v)}>{showVideo?"返回参考帧":"查看原片"}</button></div>{showVideo?<video ref={video} src="/reference.mp4" controls preload="auto" onLoadedMetadata={seekReference}/>:<img className="reference-image" src={`/reference-frames/${shot?.id}-${at}.jpg`} alt={`${shot?.id} 原片${at==='start'?'开始':at==='end'?'结束':'中间'}帧`}/>}</div></section>
    <div className="reference-row"><span>{shot?.frame}</span><div className="segmented small">{([['start','开始帧'],['middle','中间帧'],['end','结束帧']] as const).map(([key,label])=><button key={key} className={at===key?'chosen':''} onClick={()=>{setAt(key);setShowVideo(false);}}>{label}</button>)}</div></div>
    <div className="notice"><span>i</span><div><b>制作方待完成：机位标定与误差检查</b><p>你可以先核对布局和画面并提出意见。相机与背景的对齐、像素误差测量由制作环节完成；目前尚未完成，最终场景确认暂未开放。</p></div></div>
    <section className="card review-guide" id="review-guide" aria-labelledby="review-guide-title"><div className="panel-title"><h2 id="review-guide-title">用户核对指引</h2><span>先看画面，再记录问题</span></div><div className="review-steps">
      <article><h3><span>1</span>看整体空间</h3><p>在自由视角和俯视图中，看墓墙、围挡、树与山坡的前后和间距，检查物体是否落地。原片看不到的区域可记为“不确定”。</p><div className="guide-actions"><button onClick={()=>{setMode('free');showComparison();}}>看整体空间</button><button onClick={()=>{setMode('top');showComparison();}}>看俯视布局</button></div></article>
      <article><h3><span>2</span>对照不同镜头</h3><p>左侧三维与右侧原片并排看：墓墙在哪边、大小是否接近，山坡轮廓和地平线高低是否吻合。先看下列三个镜头，再查左侧其余镜头。</p><div className="guide-actions">{[['S11','正面'],['S21','反打'],['S33','正面复核']].map(([id,label])=><button key={id} onClick={()=>inspectShot(id)}>{id} · {label}</button>)}</div></article>
      <article><h3><span>3</span>记录看到的问题</h3><p>点击下方按钮带上当前镜号，写下问题，再点“保存修改与意见”。例如：“S33 墓墙在画面中太小，且偏右”。无需填写误差数值。</p><div className="guide-actions"><button onClick={noteCurrentShot}>记录当前镜头意见</button></div></article>
    </div><p className="review-footnote">当前每镜只有一个静态初步机位；切换开始／中间／结束帧只改变右侧原片参考。优先用中间帧检查背景，运镜中的偏差可以记录，后续再校准。三维端按此阶段要求不显示人物。</p></section>
    <div className="lower-grid"><section className="card"><div className="panel-title"><h2>场景物体</h2><span>{draft.nodes.length} 项</span></div><div className="asset-chips">{draft.nodes.map(n=><button className={selected===n.id?'selected':''} key={n.id} onClick={()=>setSelected(n.id)}>{n.label}</button>)}</div>{selectedNode&&<><p className="selected-label">{selectedNode.label}<small>位置 / 米 · 当前尺寸为估计尺度</small></p><div className="coordinate-fields">{['左右 X','高度 Y','前后 Z'].map((label,i)=><label key={label}>{label}<input type="number" step="0.1" disabled={selectedNode.type==='terrain'} value={selectedNode.position[i]} onChange={e=>changeNode(i,Number(e.target.value))}/></label>)}</div><p className="muted">{selectedNode.uncertainty||'选择画面中的物体或上方标签，检查其位置。'}</p></>}</section>
    <section className="card"><div className="panel-title"><h2>场景意见</h2><span>{dirty?'有未保存修改':'已保存版本'}</span></div><p className="feedback-help" id="feedback-help">全场景共用此意见框；请保留镜号，便于定位。保存意见不代表确认通过。</p><textarea aria-label="场景意见" aria-describedby="feedback-help" ref={feedbackInput} value={feedback} onChange={e=>{setFeedback(e.target.value);setDirty(true);}} placeholder="例如：墓墙应该更靠后；山坡左侧需要更高……"/><div className="save-row"><button className="text-button" onClick={load}>撤回未保存修改</button><button className="primary" onClick={save} disabled={busy||!dirty}>{busy?'保存中…':'保存修改与意见'}</button></div></section></div>
    <section className="card stage-confirmation" id="stage-confirmation"><div className="panel-title"><h2>场景确认与下一步</h2><a href="/?mode=rehearsal">从第一步演练完整流程 ↗</a></div><div className="confirmation-checks"><span>✓ 所有镜头共用固定空场景</span><span>○ 制作待完成：机位标定与误差报告</span></div><div className="confirmation-next"><div><b>如果对当前场景没有意见，点击右侧继续演练</b><p>演练会记录“假设通过”，进入角色确认，再依次查看关键姿态、完整镜头与导出。正式验收状态保持待完成。</p>{dirty&&<p className="unsaved-reminder">有未保存的修改，请先点击“保存修改与意见”，再继续。</p>}</div><button className="primary rehearsal-next" onClick={rehearseNext} disabled={busy||dirty}>{busy?'处理中…':'演练通过 → 角色确认'}</button></div><div className="formal-approval"><span>{project.approval.status==='approved'?'场景已正式确认':'正式确认将在机位标定与误差检查通过后开放。'}</span><button onClick={confirmScene} disabled={busy||dirty||project.quality.cameraMeasurement!=='passed'||project.approval.status==='approved'}>{project.approval.status==='approved'?'场景已正式确认':'确认场景通过'}</button></div></section>
    <details className="details"><summary>查看场景依据与当前镜头说明</summary><p>{camera?.note}</p><ul>{draft.reviewNotes.map((n,i)=><li key={i}>{n}</li>)}</ul><p>当前保存：{project.revision} · 场景：{draft.revision} · 历史版本 {project.history.length} 个</p></details>
  </main></div>{message&&<div className="toast" role="status"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}</>;
}
const root=createRoot(document.getElementById('root')!);
const params=new URLSearchParams(location.search);
if(params.get('mode')==='rehearsal')import('./Rehearsal').then(({Rehearsal})=>root.render(<Rehearsal/>));else if(params.get('mode')==='scene')root.render(<App/>);else if(params.get('lab')==='rig')import('./rig-lab').then(({RigLab})=>root.render(<RigLab/>));else import('./studio').then(({Studio})=>root.render(<Studio/>));
